import React from 'react'
import { motion } from 'framer-motion'

const Dashboard = () => {
    return (
        <div className=' w-full flex flex-col-reverse md:flex-row  items-start justify-start'>
            {/* MEET RECORD */}
            <div className='w-[100dvw] md:w-2/3 h-full  p-10 text-justify'>
                <h4>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugiat repudiandae quasi facere doloremque molestias neque laboriosam sed alias reprehenderit impedit tenetur, quam et dolorem dolore quo eius dignissimos sint ab.
                    Voluptate natus numquam corporis sint culpa possimus voluptatem libero voluptatibus, debitis sapiente eius quod qui amet. Pariatur nulla eum quibusdam animi laudantium, consequatur culpa vitae doloribus laborum deserunt! Sapiente, voluptas.
                    Et necessitatibus soluta vitae expedita, esse voluptate ut quis vel, architecto nihil, fugit earum. Consequatur placeat sit suscipit quidem. Veniam doloremque enim rem soluta animi blanditiis vel voluptates adipisci ullam.
                    Excepturi consequuntur explicabo voluptatem quos nostrum temporibus dignissimos? Commodi necessitatibus nam exercitationem tempore incidunt sapiente velit voluptates similique pariatur dignissimos illo minus unde, porro voluptatibus iste. Accusantium consequuntur in eos.
                    Facere quam impedit rem vel harum ad cumque! Tempore atque aspernatur fuga harum placeat, neque autem inventore deserunt maiores ratione quos ex animi beatae maxime sequi ut soluta obcaecati debitis!
                    Molestiae, velit dolore quibusdam exercitationem vitae aperiam eligendi, et officiis, quos at nulla quaerat earum tempora corporis necessitatibus nemo sint. Ullam quo hic alias saepe distinctio maiores assumenda aliquam in!
                    Eum voluptas alias harum sed voluptates officia perferendis! Ipsum, impedit dolorum. In odit nemo esse expedita sequi corrupti totam possimus animi officiis, nobis, numquam neque, vitae molestiae. Qui, illum voluptatum.
                    Fugiat unde laudantium perspiciatis. Laborum dignissimos autem molestiae corrupti saepe quo reiciendis incidunt rerum, iste at ea minus corporis adipisci iure asperiores totam sint similique aliquam mollitia voluptatem quisquam odit?
                    Suscipit rerum libero voluptatibus, perspiciatis non laudantium dolor eaque voluptatum aspernatur recusandae consectetur aliquid vero voluptate ad corrupti necessitatibus dignissimos iusto facilis? Nam ipsa et ea fugit nesciunt nemo voluptates?
                    Delectus pariatur dignissimos, labore minima mollitia doloribus vel facilis ipsa ipsam sint, eius dolorum, quisquam natus fuga! Porro expedita fugit facere! Ullam debitis recusandae tenetur natus, iste numquam repellat voluptate.
                    Expedita reiciendis soluta repellendus cum, eum asperiores ipsum doloribus ab odio nihil aspernatur accusantium amet! Doloremque fugit vero necessitatibus exercitationem fugiat quam aliquid esse aliquam, et voluptatibus minima nobis quae?
                    Quia iure vitae mollitia corrupti vero reprehenderit dolore, suscipit, ipsa temporibus voluptatem neque obcaecati cumque autem aliquam sapiente ratione excepturi maxime inventore optio et! Ex dolor atque possimus consectetur amet.
                    Consequuntur doloremque dolorum saepe distinctio earum eos veritatis magnam! Cupiditate consequuntur, pariatur totam quis sed, at omnis architecto reprehenderit tempore natus, repellat iure cum. Voluptatum accusamus aperiam eos eaque minus!
                    Quibusdam odit inventore pariatur architecto. Non voluptatum nulla vitae nostrum officia ea molestias explicabo pariatur iste. Laboriosam, expedita tempore velit officia possimus sit laborum tenetur blanditiis beatae consequuntur quas sequi!
                    Optio iusto quis harum quos modi ipsum eos? Officiis culpa sit suscipit enim reprehenderit tempore facilis nesciunt fuga autem quae ut corporis ea, dolorum amet cupiditate fugit repellat excepturi tenetur!
                    Fuga ducimus fugiat rem quos sit, dignissimos similique ea vitae repellendus officia eligendi, quo suscipit nam est dolorum iusto minima neque obcaecati quae tempore repellat accusamus totam ut? Suscipit, impedit.
                    Quae sapiente natus perspiciatis sint ad earum esse debitis! Esse pariatur possimus labore nulla aperiam eius itaque perferendis quasi qui tenetur fugiat quae deleniti, veniam tempora vel voluptates! Velit, laudantium?
                    Unde labore saepe expedita sunt officia ipsa, accusantium consequatur minima repellat deserunt facere nulla, deleniti iure autem et pariatur a alias. Sunt temporibus possimus fugiat sequi magnam dolorum, quos error?
                    Corporis sint blanditiis saepe, iusto ducimus incidunt vitae sapiente suscipit in quam est nobis nostrum, accusamus voluptatum rem voluptate laboriosam cumque! Dicta similique, fugit odit ipsum tempore asperiores reprehenderit dolore?
                    Quibusdam, nihil! At porro omnis, maxime inventore optio dolores cum eum commodi culpa excepturi illo delectus dolorum ex enim veritatis. Pariatur doloribus voluptatem eveniet perferendis harum expedita quas quod excepturi.
                    Distinctio quos molestiae, veniam accusantium sunt natus, consequatur exercitationem tempore eum numquam consequuntur cumque? Ex nulla quis reprehenderit molestiae enim, perferendis odio. Iure inventore distinctio reiciendis magni velit dolorum ipsa!
                    Dolor modi maxime accusantium dolore ipsum odio et qui placeat, a in facere culpa pariatur sunt accusamus iusto earum dolorum hic fugit soluta enim, deleniti harum excepturi aspernatur. Perspiciatis, impedit?
                    Sunt repellat excepturi consectetur minus eligendi fugit nemo facilis, ut eveniet vel dolores neque vero doloremque modi molestias temporibus. Similique suscipit molestiae nostrum voluptatem cupiditate nemo maxime, magnam laborum quo.
                    Aliquam ducimus qui natus perferendis sapiente vitae, dicta in fuga voluptas similique quia itaque, aliquid consectetur libero quam nobis, labore nemo. Repellendus, molestias unde. Sit atque enim laudantium odit illum.
                    Incidunt expedita dolorem, in, corporis minima quaerat odit deserunt dolorum modi, numquam recusandae exercitationem aliquam porro ducimus neque alias ratione! Impedit inventore blanditiis rerum est neque fugit itaque pariatur nisi?
                    Laborum velit voluptatibus voluptates nobis modi saepe reiciendis voluptate dicta alias. Dicta in, debitis tempore quis labore culpa consequuntur, consequatur, cupiditate corrupti deleniti nostrum repudiandae alias quidem soluta. Magni, assumenda.
                    Facilis explicabo dolorum rerum mollitia praesentium, natus consequatur modi sunt fuga neque! Alias quos asperiores iure optio porro autem labore nostrum animi perferendis, maiores placeat omnis. Suscipit perspiciatis voluptatum autem.
                    Dolores illo totam odio excepturi est quis pariatur quod facilis. Error magni excepturi accusamus optio iste delectus voluptate quia tenetur labore necessitatibus distinctio eum totam, incidunt nobis ipsam. Dolore, suscipit.
                    Ipsa ad soluta magni, accusamus aperiam necessitatibus. Voluptas vel, repudiandae modi perferendis laborum, tenetur amet mollitia quibusdam dolore dolores rerum non enim earum omnis ratione porro, accusamus hic eos cumque?
                    Tempore culpa inventore earum nobis dolor rerum, dignissimos vitae ut alias est cumque accusamus ea animi ad quidem, quia ullam dolorum commodi debitis? Esse vel non aspernatur cumque saepe autem!
                    Laboriosam provident itaque culpa beatae? Aperiam accusantium doloribus optio ullam nobis repudiandae. Eum nesciunt earum dolore doloribus odit assumenda explicabo rerum deleniti, qui cupiditate distinctio aliquam tempora magni nisi repellat.
                    Quo ea inventore repudiandae maxime nihil atque vel dolores dicta id! Aut perferendis voluptatem neque impedit doloremque velit perspiciatis quasi unde voluptates! Rem, libero animi eius perferendis et eum. Dolore.
                    Quibusdam accusamus consequatur vel repellat numquam in modi architecto quae impedit provident rerum sequi natus deserunt, eum rem earum eveniet iste eligendi. Ipsam eum, quia inventore iusto architecto distinctio veritatis.
                    Quod adipisci cupiditate nemo, eaque fuga labore, at ab quaerat consectetur accusantium, deserunt nesciunt ipsa laudantium dolores aliquid natus. Sed alias magnam cum exercitationem necessitatibus officiis voluptatibus, quasi blanditiis commodi.
                    Placeat incidunt, impedit sequi saepe velit obcaecati culpa perferendis expedita laborum harum optio ad quidem commodi porro molestiae quas ullam, alias repudiandae. Sequi iure voluptate placeat aliquam quis aut amet?
                    Consequatur rem dolores repudiandae veritatis nisi obcaecati illo sint? Numquam veniam error harum aspernatur, necessitatibus impedit laborum quae a, quibusdam tempora facilis saepe labore incidunt beatae reiciendis! Incidunt, dolores sint.
                    Eligendi vitae consequuntur, quaerat sequi suscipit ipsam beatae nihil nisi temporibus, omnis molestiae esse obcaecati. Ipsa vero recusandae officiis numquam beatae incidunt distinctio, quibusdam, inventore, soluta delectus ab alias hic.
                    Asperiores odit enim blanditiis veritatis tempore ad error vel! Recusandae, voluptatibus fuga! Ad alias enim repellat sequi neque recusandae vitae corporis autem tempora, corrupti iure, dolorem, tenetur architecto obcaecati dolore.
                    Iure commodi repellat quisquam harum inventore accusamus? In ratione tempora nam nobis nisi deleniti maxime quasi explicabo consequuntur natus. Eum officiis quis repellat, nesciunt quaerat ipsum iusto quae totam dicta.
                    Ratione neque iure voluptates recusandae nobis ab, consectetur eius rem reiciendis sed accusantium quo esse tenetur dignissimos cum animi perspiciatis laborum corrupti maiores incidunt eligendi! Incidunt expedita beatae odit inventore?
                    Ea autem numquam distinctio eligendi libero deleniti nemo obcaecati repudiandae assumenda. Minus, saepe facere quasi, illum vel dicta magnam, sequi porro assumenda dolores vero sapiente repellat nemo enim. Inventore, voluptatum.
                    Nostrum possimus beatae voluptas inventore, ut fugiat debitis aut cumque recusandae veniam itaque magnam voluptates repudiandae obcaecati repellendus quibusdam nihil ea in maiores, reiciendis quis provident asperiores modi! Sint, esse.
                    Obcaecati, incidunt! Exercitationem non consequuntur iste deserunt dolorem delectus tenetur a sunt pariatur ut necessitatibus minus, omnis, illum tempora ullam dicta cumque fuga, iure atque laborum esse porro labore quibusdam.
                    Eum repellendus veritatis, ipsam suscipit, temporibus, impedit voluptatibus ullam soluta eos beatae distinctio ipsa natus atque odio! Architecto facere rem, aliquam veritatis suscipit impedit cum! Consequuntur cumque aliquam ipsa eligendi?
                    Praesentium, inventore culpa nobis molestiae ab aliquid quaerat libero! Nihil sit quisquam porro voluptates alias. Nostrum, modi ad quisquam accusamus cum illo suscipit sit maxime, minima fugit sapiente! Incidunt, soluta!
                    Ad magni tenetur natus quia saepe, magnam illum pariatur obcaecati fugiat voluptas ratione, cum ullam recusandae quas temporibus deleniti quod, vel incidunt architecto ipsam nostrum fugit! Laborum recusandae vitae illum!
                    Nesciunt incidunt repellat reiciendis corrupti libero a iusto esse eius aliquam nihil in quod necessitatibus, quae dignissimos saepe. Quo ratione velit, esse itaque dolorum harum labore voluptatibus illo enim perferendis.
                    Quisquam, pariatur eius ducimus, ipsam id nisi in esse expedita ipsum saepe possimus dolor molestias nesciunt deserunt itaque voluptates quam aliquam numquam cumque eligendi. Nam incidunt impedit iure voluptates quaerat!
                    Alias velit voluptas quibusdam suscipit, praesentium in voluptatem sequi exercitationem maiores accusantium, rem eos dicta dolore ab aliquam! Quia aperiam in corrupti facere quam amet tenetur. Mollitia officiis quasi error.
                    Rem repellendus illo hic, nulla sit officiis? Qui doloremque reprehenderit, porro assumenda voluptates earum amet error inventore velit veritatis, eaque ex maiores nam eum facere. Fuga eligendi alias eaque a.
                    Minima quas cupiditate asperiores labore tenetur voluptatum, totam, eligendi expedita perspiciatis voluptate et commodi earum quibusdam distinctio quaerat sit, sequi necessitatibus maiores saepe exercitationem laborum. Deleniti hic officiis incidunt laudantium?
                    Nihil natus at sit! Eius consectetur, iste aut magni sunt deserunt, voluptates dolore molestias totam odio laborum praesentium quasi aliquam culpa? Eum accusantium explicabo voluptates rerum beatae. Molestias, at et.
                    Illo culpa facere sint iusto hic laborum, consequatur numquam odio eos mollitia alias ex ducimus tenetur ad perferendis! Dolorum culpa laboriosam earum repellat laborum est! Eaque provident repellendus sint magni?
                    Molestiae, aliquam doloremque eaque corporis et, quaerat quae magni iusto, ipsam ipsa architecto ex vero fugiat totam amet. Velit repellat voluptatibus inventore minima repellendus sunt aut iusto quae doloremque! Rerum.
                    Numquam officiis necessitatibus eos. Enim quo sit vero. Quia iure eligendi modi voluptatum, ipsam repellat. Magnam autem culpa nemo officiis asperiores tempora quia esse temporibus, quisquam omnis corporis. Dolore, rem.
                    Itaque, similique voluptatem. Soluta maiores fugiat eos error modi, ducimus voluptatem, facilis dolores vero porro officia neque. Aperiam maxime a qui, nostrum rerum odit, libero molestias impedit distinctio amet aut?
                    Debitis, odit impedit nulla ducimus non incidunt! Eligendi quibusdam incidunt quas, praesentium vel expedita facilis aut autem sequi officia ex magnam neque at, saepe maiores distinctio cumque ullam. Architecto, sapiente!
                    Rem porro vel fugiat vitae maiores nesciunt accusantium. Ut velit quos blanditiis quibusdam tempora, dolor similique, debitis repellat, iste reiciendis laboriosam ducimus labore iure cum harum accusamus porro ad veniam!
                    Sit animi mollitia voluptate sint aliquam vero nam, iste vitae velit maiores nostrum repellat repellendus eius obcaecati saepe reprehenderit quae. Laboriosam ea architecto error sunt dolores qui. Nemo, ad deleniti!
                    Quasi libero natus maiores quis repudiandae voluptatem dolores reprehenderit cum eveniet, laborum at veniam tenetur doloribus odit iste ducimus harum itaque sequi sint optio molestiae? Culpa illum nemo corrupti eligendi?
                    Placeat quas eius sapiente, quo officiis expedita nulla consequatur voluptatibus explicabo? Ratione reprehenderit totam velit provident nihil, et reiciendis nisi dolore, delectus iste itaque ullam necessitatibus ea minus eaque sequi!
                    Cumque maxime ratione beatae ipsa quo voluptatum, earum in nihil minus magni officia, assumenda, incidunt cupiditate ullam exercitationem alias quasi obcaecati itaque numquam! Ducimus modi itaque non earum soluta eaque.
                    Nesciunt magni modi, esse quia, laboriosam ut eveniet nemo assumenda facilis est minus pariatur provident accusantium quasi! Nostrum, saepe? Quasi, obcaecati! Sequi, esse. Est recusandae vitae hic! Expedita, quas tempore.
                    Culpa quasi sequi est hic modi obcaecati cupiditate odio recusandae corrupti possimus magni odit, illo quia et accusamus ex minus saepe itaque? Nesciunt enim ad, a molestiae cumque minima eaque!
                    Velit in pariatur provident exercitationem error distinctio dicta ducimus iste consectetur sapiente asperiores animi temporibus earum illum consequatur unde quaerat perspiciatis voluptate ipsum ex expedita, dolore tempore mollitia? Veniam, reprehenderit.
                    Odit, aliquam reiciendis consectetur perferendis, voluptates quam modi numquam expedita hic similique veniam tempora perspiciatis sapiente non repellendus, beatae assumenda labore temporibus commodi atque ab quae repudiandae laudantium! Dolorem, cumque.
                    Sed sit dolorem atque rerum, nam aperiam doloribus natus rem nulla, consequuntur vel quod eos autem incidunt corrupti excepturi vitae, ducimus pariatur! Vero, soluta necessitatibus neque odio labore beatae itaque!
                    Neque voluptatem iusto obcaecati, veritatis incidunt eius similique minus non earum accusantium aliquid, vel eum? Reprehenderit praesentium ipsa eaque inventore animi molestias impedit quo cumque, commodi a, tempora omnis deserunt.
                    Officia voluptas vel omnis expedita, delectus porro sit ipsum aspernatur officiis maiores amet quam assumenda commodi corporis nisi possimus deleniti nesciunt nobis non labore. Quae autem quaerat minus nihil cupiditate.
                    Ipsam minus repudiandae iusto quam laborum sed dolorum enim beatae ipsa eveniet facilis optio ad eligendi necessitatibus, error aperiam similique vero amet quas eos libero impedit nulla quasi placeat. Doloremque.
                    Consequuntur accusamus soluta quisquam sit praesentium temporibus facere repudiandae accusantium voluptatum at optio quod iusto, laudantium consectetur in! Eum nulla ab nesciunt beatae est! Suscipit enim ad sed ut accusantium?
                    Odio molestias rerum doloremque cupiditate accusamus expedita nobis amet, quidem accusantium, facere omnis tenetur? Quos deleniti dignissimos numquam repudiandae recusandae eveniet harum, pariatur consectetur accusantium cupiditate, hic veniam cumque eum.
                    Corrupti laudantium veniam nesciunt harum quibusdam. Ut, fugit? Cupiditate unde id modi praesentium ullam. Voluptatem nisi, fuga officiis dolor animi molestias ullam similique minus doloremque dolore eius aperiam veniam placeat!
                    A laborum eum, ut ab accusamus, suscipit perspiciatis dolor eius officia perferendis rem molestias soluta alias, architecto corporis natus pariatur sequi cumque esse? Pariatur porro aliquam quis nulla debitis asperiores.
                    Veritatis optio debitis vero unde officiis, cupiditate laudantium libero harum, voluptatibus doloremque hic nobis minima! Magnam, iure soluta autem atque necessitatibus veniam, similique accusantium vero cumque aliquam praesentium libero quibusdam.
                    Sunt, fugiat iusto! Fugiat reprehenderit dolorem ut, odio autem veritatis quam perspiciatis doloribus quae, magnam aperiam! Fugiat voluptatum ipsum praesentium architecto possimus rem porro veritatis sunt? Officiis illum explicabo nesciunt.
                    Tempore, quas. Nulla voluptas accusamus aperiam quis illum totam dolor laboriosam inventore, assumenda reprehenderit delectus corporis, ducimus cumque consequuntur mollitia quasi error perferendis molestiae quae, amet numquam sapiente harum nostrum!
                    Obcaecati iusto perspiciatis nihil natus eaque id cum hic. Illo veritatis animi illum, saepe repudiandae error dignissimos, rem quasi cum et odit consequuntur recusandae, quidem totam accusantium voluptate atque perspiciatis.
                    Beatae officia nesciunt eligendi saepe id illo pariatur rerum earum quidem vitae. Sed, explicabo mollitia. Architecto saepe quis illo facilis magni eius quam mollitia in. Enim, non mollitia! Non, suscipit!
                    Rem odit laborum tempore perferendis eos suscipit, blanditiis illo veniam fugiat soluta nemo, unde, doloribus quaerat obcaecati numquam pariatur distinctio modi rerum dolorum aspernatur explicabo? Ab dolorem iure fugiat blanditiis.
                    Quod libero molestias, architecto dolorem recusandae expedita explicabo? Eos modi incidunt, suscipit eligendi veritatis, expedita nesciunt consequatur natus ratione voluptas aspernatur earum rem architecto a est cumque neque nulla id?
                    Culpa esse necessitatibus sed blanditiis. Corporis ad eos perspiciatis iusto esse aperiam, reprehenderit magnam quaerat dicta odit eaque iure, sint eveniet animi ipsa necessitatibus facilis facere. Obcaecati doloribus accusantium neque?
                    Ab, tempore. Aspernatur iste facilis facere veritatis placeat libero reiciendis eveniet. Magnam, est cum minima optio atque quae, dolorum amet facilis sit, animi eveniet dolor? Odit aperiam nostrum vero magnam.
                    Tempore accusamus cupiditate quisquam soluta perferendis earum debitis voluptate suscipit, modi, sapiente beatae ad officia nisi quos! Laboriosam mollitia accusamus pariatur, ratione ex dolores nesciunt, facilis ea quidem, sint aut?
                    Officiis quisquam, earum eaque, voluptates assumenda cupiditate fuga quidem laborum numquam eligendi saepe expedita illo doloremque a ipsa quasi perspiciatis reiciendis eum dolorum exercitationem! Vero ad nihil odio placeat quaerat.
                    Amet maxime molestiae delectus in veniam velit nihil laboriosam, deserunt aliquam ab neque ea vel sed cum dicta molestias officia enim dolores ducimus quaerat pariatur? Quam consequatur soluta necessitatibus ea.
                    Quae iste eaque consequatur nemo debitis error officiis, reiciendis non animi omnis officia autem illum, alias fuga similique fugit esse totam rerum ut. Eaque et facilis quis laboriosam magni repellendus.
                    Aperiam quos enim debitis, explicabo maxime iure, assumenda doloribus, alias optio perferendis perspiciatis voluptatum eos nisi dolor fugiat repellendus delectus. Dicta repudiandae, neque nesciunt ex iusto sit distinctio doloremque delectus.
                    Accusamus similique expedita dolor corrupti adipisci ducimus sed aspernatur non incidunt voluptates consequatur amet voluptatibus vel voluptas aliquid ex nulla, ea numquam culpa repudiandae. Consequuntur libero numquam aliquid placeat. Quasi.
                    Assumenda ab aliquam laborum corrupti iusto veritatis voluptatem reiciendis provident omnis, laudantium facere accusantium tenetur vero maxime itaque. Officiis cumque eum reiciendis suscipit, in voluptate necessitatibus nihil sapiente sunt minus.
                    Tempore, necessitatibus eveniet corrupti alias similique voluptates consectetur nulla, facere eum corporis, beatae praesentium mollitia architecto quaerat quas quos hic veritatis. Esse beatae omnis neque quas consequuntur itaque tenetur delectus.
                    Tenetur eius voluptate natus ipsum quo, eveniet sequi, expedita dolore ad fugit minima, harum pariatur. Laudantium repellat neque error eaque eius nulla voluptates expedita, maiores libero soluta cum distinctio animi!
                    Tempora vel totam, optio soluta aut adipisci voluptatem, deleniti tenetur sit tempore enim commodi quos culpa quam. Hic pariatur ullam quasi, quibusdam, asperiores architecto reiciendis ea obcaecati itaque corporis aspernatur!
                    Quia id atque sunt dolorum cum ipsam laborum neque nam nobis fugit, perferendis vitae, odit rem culpa quibusdam. Harum adipisci iste, aliquam architecto ipsum ducimus explicabo consectetur! Accusantium, beatae accusamus.
                    Consectetur maxime provident culpa doloribus distinctio magnam fugiat rem ducimus, quo facilis sunt reiciendis, velit ea voluptate repudiandae, tempora nemo? Quae, quibusdam. Delectus omnis repudiandae blanditiis natus doloribus, saepe eligendi.
                    At placeat consectetur, nobis ratione eligendi neque maxime repudiandae nulla error impedit nihil numquam expedita, sit corrupti laborum adipisci quia iure dolores. Repudiandae sit quisquam, odio culpa non earum iure.
                    Ipsum repudiandae perferendis molestiae odio nisi quam, vitae aliquid accusamus maiores suscipit ut numquam doloribus maxime harum incidunt mollitia necessitatibus accusantium assumenda laboriosam, voluptas voluptate provident. Ipsum rem odit aspernatur!
                    Illum aliquid vitae, praesentium sit doloremque dolorum porro autem pariatur incidunt enim nesciunt! Tempora eaque quos ut aut facilis officiis. Odio perferendis eveniet blanditiis placeat autem corporis fugit ab quisquam.
                    Laboriosam, neque? Ex, quod. Ipsa, dolore exercitationem! Aliquam quaerat voluptatibus laudantium in. Molestias laboriosam dolores totam expedita? Error ipsa vel provident saepe natus sint totam optio, dignissimos nobis nesciunt laudantium!
                    Voluptates impedit id officiis autem soluta asperiores laboriosam aut reiciendis nesciunt ab nulla aliquid quisquam ad amet veritatis, fugiat illum ut laborum. Suscipit quos facere earum incidunt fugiat dolor possimus!</h4>
            </div>

            {/* SECTION 2 */}
            <div className='p-5 w-[100dvw] md:w-1/3 md:h-[calc(100%-60px)] border-l border-[var(--header-border)] md:fixed md:right-0  flex flex-col items-center justify-center'>
                {/* ADD BOT CARD */}
                <motion.div
                    initial={{ opacity: 0, x: 100 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.5, type: "spring", stiffness: 50 }}

                    className='h-[400px] md:w-[440px] md:h-[400px] relative py-12 px-6 bg-[var(--bg-card)] shadow-md border border-[var(--bg-main)] rounded-3xl  '>
                    <p className='text-4xl font-[500] text-[var(--primary)] text-end'>Add bot to meeting</p>
                    <p className='text-sm opacity-80 w-[300px] float-end font-[200] mt-6 text-[var(--primary)] text-justify'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus perferendis nesciunt repudiandae repellendus! Placeat veniam accusamus possimus illum cum deserunt error mollitia, adipisci reprehenderit quibusdam veritatis, odit, rem minima dolore.</p>
                    <button
                        className='active:scale-95 text-[var(--button-text)] absolute rounded-md bottom-10 right-6 px-6 py-1 text-lg bg-[var(--button-color)]'>
                        Add
                    </button>
                </motion.div>
            </div>
        </div>
    )
}

export default Dashboard